### ISSUE TITLE
Log for which trajectory point finding a candidate fails

### ISSUE THREAD

**Issue by kimsey0** [jagodki/Offline-MapMatching#15]
Currently, when `HiddenModel.createGraph` fails to find a candidate for a trajectory point, `MapMatcher` just logs a generic error message: _the maximum search distance is too low for one trajectory point point to find at least one candidate_. Could it additionally log the ID of the point for which finding a candidate fails? This would ease debugging.

**Comment by jagodki** [comment]
I uploaded a new version of the plugin (2.2.0) with the changes into it. Thank you for your work 👍

**Comment by kimsey0** [comment]
You're welcome. Thanks for handling this so quickly and positively. 😄
