### ISSUE TITLE
get test data

### ISSUE THREAD

**Issue by wangjnchuan** [jagodki/Offline-MapMatching#19]
hi, I want get some test data, can you send to me, thank you!
my e-mail: wangjnchuan@163.com

**Comment by jagodki** [comment]
Hi, I uploaded two short trajectories, that I was using during the development. I also uploaded a road network of the city of Radebeul, Germany (extracted from OSM). You can find the data in the [testdata-folder](https://github.com/jagodki/Offline-MapMatching/tree/master/testdata).

If you want more trajectories, just use an app for your mobile phone to measure your position during a walk (their are several free apps available for both, android and iOS). Than you can get your one trajectory for testing or something else 😺
