### ISSUE TITLE
Issue:001 - Can't open trajectory

### ISSUE THREAD

**Issue by Redoute** [jagodki/Offline-MapMatching#2]
I want to try this plugin. In a new project I load a network layer "netz" from PostGIS, and a trajectory layer "gpxneu" as shapefile. The shapefile is made from a recorded gpx file, track points, translated to EPSG 32632 (same as project and layer "netz").

In the plugin dialog, I can select layer "netz", but the popup list Trajectory-Layer is empty.

On a freshly installed QGIS 3.2.1, Windows 10.

**Comment by Redoute** [comment]
My point layer is of type Point25D, but MapMatcher.fillLayerComboBox() only considers `layer.Type() == QgsWkbTypes.Point`. I try changing this to `layer.geometryType() == QgsWkbTypes.PointGeometry`.

**Comment by jagodki** [comment]
@Redoute sorry for my late response. I can reproduce the bug and working on a solution.

**Comment by jagodki** [comment]
@Redoute solved with version 1.0.3 (using QgsWkbTypes.flateType(...) to enable layers with Z- and/or M-values in their geometries)
