### ISSUE TITLE
Error during calculation of transition probabilities

### ISSUE THREAD

**Issue by CateDeku** [jagodki/Offline-MapMatching#21]
Hi, i'm trying to use this plugin, but i keep getting error message.
I have as a network layer an Open Street Map exported from their web site, and a series of GPS points as track layer.
The tool start map matching, but then suddenly stops, giving me this error: "Error during calculation of transition probabilities".
Any suggestion?

**Comment by jagodki** [comment]
Hi,

this error will be raised during the calculations of the transitions, where the direction between the two candidates (the start end end point of the transition) on the network will be compared to the direction between corresponding trajectory points. Also the distance on the network between the candidates and the the euclidean distance of the trajectory points are calculated and compared.

It can be, that the routing between the candidates is not successful, because they are not connected on the network. If the trajectory is not at the boundary of the network, you could try to decrease the maximum search distance. It could be possible, that at the boundary of the network are some line strings, that are not properly connected to the rest of the network.

You can also provide me the data, if possible and allowed, so that I can try to figure out the problem and debug the plugin with you data. Or you could share a screenshot of you trajectory and network in this issue to get some feeling for your data and possible problems.

Sincerely,
Christoph

**Comment by CateDeku** [comment]
[20190722043818-56173-data.zip](https://github.com/jagodki/Offline-MapMatching/files/3417816/20190722043818-56173-data.zip)
[2019-05-09 1244 polo mep__20190509_1244.zip](https://github.com/jagodki/Offline-MapMatching/files/3417818/2019-05-09.1244.polo.mep__20190509_1244.zip)


Thank you for your answer. These are the data. 
I have selected the first one as network layer, and "polo mep" as the trajectory to be matched.
I noticed that the error occur when the selected network layer has more than one <trkseg> tag

**Comment by jagodki** [comment]
Hi,

thank you for providing the data. The next days I will have a look on it. I hope I can find an answer for your problem until the weekend.

Sincerely,
Christoph

**Comment by jagodki** [comment]
Hi,

your data has the CRS EPSG:4326, i.e. the coordinates are in degrees. My plugin calculates distances , so a metric CRS is recommended. Your data is localized in Somalia and I do not know, which CRS is recommended for this region.

First I tried to reproject the data into EPSG:20538. I do not know why, but my QGIS has some problems with this CRS. It does not recognize it correctly if I import data with this CRS into a blank project. And the plugin stopped in the middle of the calculations, as you wrote.

Second I tried the CRS EPSG:32638. Now it works without problems:
![matching_result](https://user-images.githubusercontent.com/23242936/61736625-cd1d8e80-ad86-11e9-83e6-6a1ab4421741.PNG)

I think the selected CRS could be the problem. I am not familiar with CRS outside of Europe, so I cannot give you an explanation why the map matching will stop with EPSG:20538.

Please try to use another CRS and report your results.

Sincerely,
Christoph

P.S. The given network does not contain edges along the trajectory, i.e. the result could be a bit strange (as you can see in the screenshot above)

**Comment by CateDeku** [comment]
Hi Christoph,
thank you very much for your answer. I tried to do what you suggested, but doesn't work for me. I have reprojected all the vector in QGIS, but i still got the error message.
I will try with another network layer. How can i get in QGIS a clean network graph starting from osm data? Do you have any routine to suggest?

**Comment by jagodki** [comment]
How did you reproject your layers? Using the save to-function or via the retroject-function in the toolbox. I am not sure if there are differences for the reprojection, but it could be a good idea to avoid mistakes. I used the function from the toolbox.

To create a clean network, I am using the PostGIS-function createTopology(...), i.e. you need a PostgreSQL-/PostGIS-installation. I do not know any similar function in QGIS. But I asked in the QGIS-mailing list about it. I hope somebody knows the solution 😄

**Comment by jagodki** [comment]
I got answers from the mailing list. But no plugin or build-in function mentioned in there has the same functionality like the described PostGIS function, sorry 😿 

But it is really strange that the same network is working for me, but not for you...

**Comment by CateDeku** [comment]
Yes, it is strange. Basically i have the same problem of @love-freedom777: with the update of the plugin now i don't receive an error message anymore, but the calculation stuck and qgis freeze and crash.

I notice that i have no problem if the network is composed of an unique line with just one segment, like this:
![Screenshot (80)](https://user-images.githubusercontent.com/52274927/63500523-474a4b80-c4ca-11e9-99ea-eebcef7d34b1.png)

while the data downloaded directly from OSM have multiple segments, and this in my case creates problems:

![Screenshot (101)](https://user-images.githubusercontent.com/52274927/63500908-043ca800-c4cb-11e9-8857-2fa883583d4b.png)

**Comment by jagodki** [comment]
Hi,

Please see my last commend in #issue24. I also think, that this is the same problem. The plugin searches possible points (so called candidates) on the network for each feature/dataset/edge of the network for each trajectory point. If your network contains just one single line, the plugin finds only one candidate for each trajectory point. These candidates will be the vertices of the matched trajectory. With such a network, the computation will be fast, but the result will not be very good. Please download the processing model I provided in #issue24 to reduce your network. A description of this model is provided in #issue24. 

Sincerely,
Christoph

**Comment by jagodki** [comment]
I released a new version of the plugin. Now it offers a new function to reduce your network by buffering the trajectory and clip the network using this buffer. With a reduced network the calculations should be faster. Maybe this helps you...

Sincerely,
Christoph

**Comment by jagodki** [comment]
closed because of inactivity, please reopen this issue if necessary
