### ISSUE TITLE
Matching on junction 

### ISSUE THREAD

**Issue by brunoeducsantos** [jagodki/Offline-MapMatching#27]
Hi  @jagodki ,
The matching on junctions is not working very well. 
![map_matchingjunction](https://user-images.githubusercontent.com/3111976/62525643-aacc4c00-b82f-11e9-93f0-ad0b71ee565a.png)
Legend:
- **Red**: GPS
-  **Green**: points matched in the network
- **Blue** : graph network points
I was checking the total probabilities and they trend to zero quickly. Could that be the reason not work well on junctions?
Do you have any suggestion?
Thanks,
Bruno

**Comment by brunoeducsantos** [comment]
I found out that smoothing GPS with Kalman Filter helps

**Comment by jagodki** [comment]
Hi,

Junctions are a known problem in the field of map matching. It is not easy to avoid a wrong turn to the left or right of the trajectory with a following go back (so called u-turns). To avoid u-turns I introduced the Parameter transition weight in the plugin. But it is not easy to find the right value for it...

Smoothing the trajectory is a good idea and I will provide a possibility for preprocess the trajectory in a future version (at the moment I prepare a preprocessing of the network). Could you tell me how did you smooth your trajectory? Did you used another software, or do you have script for the Kalmen Filter (maybe open source)?

Another way could be to reduce the density of your trajectory. It looks very dense, which is a problem for the computation time. When you reduce the density you could smooth your trajectory with a statistical approach to remove outliers in the same step. 

Sincerely,
Christoph

**Comment by brunoeducsantos** [comment]
Hi,
Could you refer the parameter in the code please? Is it my ?

For smoothing the trajectory I used a script from the[ this package](https://pykalman.github.io/).

Thanks for the feedback.

Regards,

Bruno

**Comment by jagodki** [comment]
Hi,

the parameter will be used in the file <a href="https://github.com/jagodki/Offline-MapMatching/blob/master/src/offlinemapmatching/mm/hidden_states/transition.py">transition.py</a> to calculate the routing probability (function setRoutingProbability, the parameter beta is the transition weight). Please have a look on <a href="http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.187.5145&rep=rep1&type=pdf ">Newson & Krumm (2009)</a> (chapter 3.2) to get a description of this parameter. As I mentioned before, this parameter is difficult to understand and to set up, but can improve the matching results a lot. Newson & Krumm provide a formula to calculate this value. This should be implemented in the plugin, but at the moment, I do not have the time for it...

Sincerely,
Christoph

**Comment by brunoeducsantos** [comment]
Hi @jagodki ,

Thanks for the reference. It looks a very good resource.
I might try to implement later the beta formula. I will keep you posted.

Regards,
Bruno
