### ISSUE TITLE
Running error

### ISSUE THREAD

**Issue by zyyecjtu** [jagodki/Offline-MapMatching#30]
Hello, I recently used this plugin because of work, but the software crashes when I am in "start map  matching". I would like to ask you to check if there is a format problem with the road network file and GPS data(all in data.zip). thank you!
[data.zip](https://github.com/jagodki/Offline-MapMatching/files/3630173/data.zip)

**Comment by jagodki** [comment]
Hi,

does QGIS crashes or just the plugin? If just the plugin, please open the QGIS-log. The plugin writes all errors and processing steps into the QGIS-log. The error message would be very helpful for me to find the problem. I will control your data during the next days...

Sincerely,
Christoph

**Comment by zyyecjtu** [comment]
Hello、
I am very grateful to hear from you. The software crashed, and the plug-in has been stuck at 37%, almost no movement, the log shows that the plug-in is still in the calculation. I suspect that there is a problem with my data, but I have not found it. Waiting for good news, thank you.
Sincerely、
zyy
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Christoph"<notifications@github.com&gt;;
发送时间:&nbsp;2019年9月20日(星期五) 下午5:57
收件人:&nbsp;"jagodki/Offline-MapMatching"<Offline-MapMatching@noreply.github.com&gt;;
抄送:&nbsp;"Sgr A*"<1821167745@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [jagodki/Offline-MapMatching] Running error (#30)




Hi,
 
does QGIS crashes or just the plugin? If just the plugin, please open the QGIS-log. The plugin writes all errors and processing steps into the QGIS-log. The error message would be very helpful for me to find the problem. I will control your data during the next days...
 
Sincerely,
 Christoph

**Comment by jagodki** [comment]
Something is not correct with your data. If I can see the whole reduced network, the map scale is something like 5:1 or 10:1 (depending on the window size). That means your geometries are too small. A map scale like 1:n with n greater 1 should be normal. Because of this, the plugin finds many candidate points on the network if you choose a maximum search distance greater one. This many candidate points are the reason for a very very long computation time. If I insert a maximum search distance of 0,001 meters, I get a result after ca. one minute. 

Please try to use this search distance and tell me, if it now works. If it works, you should have a look an your data. Maybe something went wrong with reprojection or something else. 

Sincerely,
Christoph

**Comment by zyyecjtu** [comment]
Thank you very much for your reply. I just downloaded the map on the Openstreetmap website and adjusted the projected coordinate system (the original map's coordinate system is wrong). The plugin can now be applied. Thank you for your patience.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Christoph"<notifications@github.com&gt;;
发送时间:&nbsp;2019年9月24日(星期二) 晚上6:57
收件人:&nbsp;"jagodki/Offline-MapMatching"<Offline-MapMatching@noreply.github.com&gt;;
抄送:&nbsp;"Sgr A*"<1821167745@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [jagodki/Offline-MapMatching] Running error (#30)




Something is not correct with your data. If I can see the whole reduced network, the map scale is something like 5:1 or 10:1 (depending on the window size). That means your geometries are too small. A map scale like 1:n with n greater 1 should be normal. Because of this, the plugin finds many candidate points on the network if you choose a maximum search distance greater one. This many candidate points are the reason for a very very long computation time. If I insert a maximum search distance of 0,001 meters, I get a result after ca. one minute.
 
Please try to use this search distance and tell me, if it now works. If it works, you should have a look an your data. Maybe something went wrong with reprojection or something else.
 
Sincerely,
 Christoph

**Comment by jagodki** [comment]
Great to hear, that it now works :)
