### ISSUE TITLE
Count number of overlapping map matched GPS trajectories with road network

### ISSUE THREAD

**Issue by rvinogradov** [jagodki/Offline-MapMatching#35]
Hi, I successfully map matched a sequence of GPS-points to a road network using the Offline-Map Matching plugin. This map matched trajectory passes certain roads segments multiple times (for example, the selected red matched trajectory segment in the picture below has two unique fid numbers, 60 and 359, see left).

In order to visualise where most vehicle activity occurred in the network (with the line thickness/size being proportional to the number of overlapping map matched trajectories), I need to analyse the number of overlapping map-matched trajectories in the road network.

I have tried several things but unfortunately without success. Any ideas on how to do this in QGIS?

![Screenshot 2020-03-30 at 09 43 05](https://user-images.githubusercontent.com/40352112/77894057-0a6ee000-7275-11ea-86c4-a44bbb67707d.jpg)

**Comment by jagodki** [comment]
Do you just need a visual presentation in the map or do you want to store the activity of passing road segments in your network-layer too? I think both should be possible. Please give me some days to find the time for solving this task :)

**Comment by rvinogradov** [comment]
I would like to store the activity of passing road segments in my network layer, and make a visualisation based on that. Thanks a lot!

**Comment by jagodki** [comment]
Have a look on the function "Join attributes by location (summary)":
<img width="308" alt="image" src="https://user-images.githubusercontent.com/23242936/78059723-a9393080-738a-11ea-954b-3bdfbf6a51d1.png">

I used the road network as the input layer and the matched trajectory as the join layer. Furthermore I used the id field for the summarise and calculated the count.

<img width="800" alt="image" src="https://user-images.githubusercontent.com/23242936/78059940-0634e680-738b-11ea-9a5f-3271e817c5ba.png">

The result layer will have a new field called id_count with the count of map matched lines intersecting the road network into it. This field can be used for a graduated styling (darker road segments were passed more often):

<img width="856" alt="Bildschirmfoto 2020-03-31 um 19 55 05" src="https://user-images.githubusercontent.com/23242936/78060114-472cfb00-738b-11ea-9623-506ec9fe59d8.png">

Does this function fits your needs?

**Comment by rvinogradov** [comment]
Unfortunately not. An intersection between the matched trajectory segments and road network will yield incorrect results because side streets will intersect the matchted trajectory too and therefore generate a count aswell (see below)
![Screenshot 2020-04-01 at 10 26 40](https://user-images.githubusercontent.com/40352112/78115684-73845e00-7403-11ea-8817-b2e83b754532.jpg)

I have tried 'overlaps' as geometric predicate aswell, but that also gives strange results (see below). The problem is that the matched trajectory segments are not consistent in length with the road segments. So the challenge is to find a way to take care of that.

![Screenshot 2020-04-01 at 10 26 44](https://user-images.githubusercontent.com/40352112/78115720-8303a700-7403-11ea-8385-51bf1f178dfd.jpg)

**Comment by rvinogradov** [comment]
A possible solution might be to convert the map matched trajectory into points using the Points Along Geometry tool. I have tried that using a distance of 10 meters and a Start and End offset of 1 meter to avoid that the first and last point fall exactly on the beginning or end of the matched trajectory lines. In this way it points will not be generated on a junction and thus side streets. However, if I use the _Join Attributes by Location tool (summary)_ again, with the _RoadNetwork_ as Input layer and the _Interpolated points_ as Join layer, I get mostly NULL values when using _Intersects_ as Geometric predicate and _Unique_ as summarisation method. Strange..

**Comment by rvinogradov** [comment]
I have created small (0,1 meter) buffers around the points and now the Join Attributes by Location (summary) tool does yield Unique id values. However, the problem is still that the lengths of the street segments are not exactly the same as the those of the matched trajectory segments.  I have tried to achieve this by running the Split Lines With Lines tool, but unfortunately without succes. Would be interested to hear if you have any other solutions.

**Comment by jagodki** [comment]
The difference between the lengths of the road segments and the segments of the matched trajectory are expectable. The vertices of the matched trajectory are candidate points, i.e. points on the road network (but not mandatory vertices of the network) that will explain the trajectory best. 

The problem with the side roads can be avoided, if you create a very small buffer around the matched trajectory (e.g. 0,1 m) and then using this buffer as a clipping mask for your network:
<img width="846" alt="image" src="https://user-images.githubusercontent.com/23242936/78183380-18d11d80-7468-11ea-8c1d-da79cacf4a3a.png">

A better visualisation could be, if you split this clipped road network in pieces of lines with a maximum length (10 m, 50 m, ...). Then you would have more or less regular line segments for the evaluation...

**Comment by rvinogradov** [comment]
Clipping the road network with a small buffer around the matched trajectory gives good results, thanks. I have also experimented with using a maximum length of 10 meters for my road network, which works reasonably well. There are still some minor road segments that register an extra trigger when matched trajectory segments overlap and as a consequence multiple points with different id's fall within that 10 meter road segment. Nevertheless I'm satisfied with the result. Thanks!
![Screenshot 2020-04-02 at 13 06 41](https://user-images.githubusercontent.com/40352112/78243532-39d75400-74e4-11ea-9806-bda57bb8d9e7.jpg)

**Comment by jagodki** [comment]
Nice to hear that I could help you 😃
