### ISSUE TITLE
Change of settings match trajectory tool does not seem to have an effect on output

### ISSUE THREAD

**Issue by rvinogradov** [jagodki/Offline-MapMatching#36]
Hi, I have used the following parameters to map match a sequence of GPS points:

![Screenshot 2020-04-02 at 13 33 29](https://user-images.githubusercontent.com/40352112/78244809-a2273500-74e6-11ea-949d-fc0ccb9684c9.jpg)

Looking at the matched trajectory in the picture below, this resulted in some incorrect matches (i.e. the map matching algorithm assumes that the vehicle entered several side streets and returned after a couple of meters to its original route). The screenshots at the bottom of the [Readme](https://github.com/jagodki/Offline-MapMatching) of your map-matching algorithm, shows a similar case. However, a succesfull match was achieved by increasing the mean difference (I assume this is the transition weight?) from 30 to 35. 

![Screenshot 2020-04-02 at 13 33 03](https://user-images.githubusercontent.com/40352112/78244822-a94e4300-74e6-11ea-994f-b1f75c224eef.jpg)

I reran the map matching algorithm with a higher transition (35) weight aswell, but unfortunately without succes; the exact same Matched Trajectory was produced. Is there something else I could try to get a more succesfull match?

**Comment by jagodki** [comment]
The transition weight is a very difficult parameter. If you want to understand it better, read in Newson & Krumm (2009) the explanation about the parameter beta (link to the paper at the end of the readme). 

According to your screenshot, I think there are two things you have to do:
1. increase the maximum search distance, maybe the following point of your trajectory just finds one candidate (use the measure tool to check it out)
<img width="375" alt="image" src="https://user-images.githubusercontent.com/23242936/78296518-2ea91600-752e-11ea-9ea5-6789f89aec95.png">
2. Increase the transition weight. The plugin uses this parameter similar to the standard deviation in a normal distribution, i.e. a higher value will flatten the curve of a normal distribution with the result of smaller differences between the probabilities of this curve. Try a value of 50 or more. I think two problems should be solved with a higher transition weight:
<img width="283" alt="image" src="https://user-images.githubusercontent.com/23242936/78297326-a166c100-752f-11ea-9ea1-e03b54c9da41.png">
<img width="349" alt="Bildschirmfoto 2020-04-02 um 22 21 04" src="https://user-images.githubusercontent.com/23242936/78297658-54371f00-7530-11ea-9551-91916be2a470.png">


I tried to copy your situation in QGIS and with the parameters max search distance = 100, standard deviation = 50 and transition weight = 50 it works very well:
<img width="809" alt="Bildschirmfoto 2020-04-02 um 22 19 38" src="https://user-images.githubusercontent.com/23242936/78297569-19cd8200-7530-11ea-8388-2cd495064187.png">

With a transition weight of 30 I get the same problems like you.

**Comment by rvinogradov** [comment]
You were right about the maximum search distance, it was too low because the blue point was at a distance of 21 meters from the road candidate it was supposed to be matched. I reran the algorithm with exactly the same parameters as you did (max search distance 100, SD = 50 TW = 50). Although it gives me slightly better results for the example situation above.. :

![Screenshot 2020-04-03 at 11 45 19](https://user-images.githubusercontent.com/40352112/78379080-26a2b200-75d2-11ea-9024-e7691348c182.jpg)

.. it generates incorrect matches in other parts of my network: 
![Screenshot 2020-04-03 at 11 46 01](https://user-images.githubusercontent.com/40352112/78379134-37ebbe80-75d2-11ea-93f8-de00bbeffb29.jpg)

Also, since I have a relatively large dataset, it took a very long time for the algorithm to complete so I will have to use a lower maximum search distance next time. (The zip file I sent you the other day via mail also contains the GPS-points and road network, in case you'd be interested to test it again).

**Comment by jagodki** [comment]
Indeed, they are really large datasets. The plugin offers a preprocessing function to clip the network. This will speed up the calculations. Could you split your trajectory into several, smaller parts? It could help you to match die difficult parts faster. Could you tell me a reasonable filter to split the trajectory?

Otherwise I currently do some literature research to 
a) make the algorithm more robust and easier to use 
b) speed up the calculations
But the implementation will take some time because I am working on another project right now. This will not help you at the moment, but someday this year, I hope I can release a big improvement for this plugin.

**Comment by rvinogradov** [comment]
Yes I do make use of the Clip Network tool to preprocess the network. But even then, it takes a very long time to calculate the path when using a maximum search distance of 100 meter.  I don't think that splitting my trajectory into smaller segments would help to prevent getting these strange map-matching results like these:

![Screenshot 2020-04-10 at 13 17 58](https://user-images.githubusercontent.com/40352112/78987318-f907bc80-7b2d-11ea-847a-04b609710b15.jpg)

Instead, it should have something to do with the settings of the match trajectory tool. I've used the following settings for the result above:

![Screenshot 2020-04-10 at 13 21 06](https://user-images.githubusercontent.com/40352112/78987405-310eff80-7b2e-11ea-9a5a-df1f8817ceaa.jpg)

Any advice on what I might try to tweak to get better results?

**Comment by rvinogradov** [comment]
Another question I had is that the matched trajectory does not seem to adhere to the driving directions of the network, for example here at the roundabout where the driving direction is obviously clockwise but the trajectory is matched anti-clockwise. 
![Screenshot 2020-04-10 at 16 29 28](https://user-images.githubusercontent.com/40352112/78998243-7d673900-7b48-11ea-8354-0ba7ce061d90.jpg)

I am using a network that is divided into links bounded on the ends with an A node and a B node, so the should be included. Is there something wrong with my network? I have included a sample of my road network in the email I sent you the other day if you would like to check it out.

**Comment by jagodki** [comment]
The problems with so called u-turns, i.e. entering side streets and returning after several meters, will I handle with the new major release I startet working on. Sometimes it is very tricky to avoid these things. At the moment I do not have a better advice for you, sorry 😞 

Roundadbouts are a new special task for the plugin. I did not spent time to test the plugin on such roads, sorry ^^ The plugin does not use any information about forbidden directions of the network. Because of this it is not unusual that the matched trajectory will pass the roundabout in the wrong direction, if the density of the trajectory in this region is a bit spare.

**Comment by rvinogradov** [comment]
Ok I see! Guess I will have to wait for the next major release then. Looking forward to that, good luck! :-)
