### ISSUE TITLE
how to get network information?

### ISSUE THREAD

**Issue by 382304045** [jagodki/Offline-MapMatching#44]
Hi, I am new to use the offline-mapmatching, after I tried some test data, I can get the Trajectory now, but I only get limited information from the Trajectory layer. I hope to know where the GPS points are on the road network. I have ID for each road link，for examp, the GPS points 1 is on the link_ID 200, the points 2 is on hte link_ID 201, and so on.
So, after I get Trajectory, I hope to know which links that the points on. How can I do it?

**Comment by jagodki** [comment]
Hi,

I am very sorry for the late response and for the fact, that the plugin does not return any information of the candidate points. Their position will only be calculated internally. But your issue is a good idea for a new version. I will integrate such function in one of the next releases (but I am not able to schedule it).

Sincerely,
Christoph

**Comment by 382304045** [comment]
> Hi,
> 
> I am very sorry for the late response and for the fact, that the plugin does not return any information of the candidate points. Their position will only be calculated internally. But your issue is a good idea for a new version. I will integrate such function in one of the next releases (but I am not able to schedule it).
> 
> Sincerely,
> Christoph

Thank you, another problem is when I can run this plugin for one trip layer and one network layer successfully, but it always froze or took a very very long time to get results when I try to use batch mode that includes more than one trips layers with the same network layer. 
Is there any way to solve it?
Thank you.

**Comment by jagodki** [comment]
Mh, I have not so many experience with the batch mode of the plugin. Does it freeze for a specific trajectory or can you repeat it with different data?

**Comment by jagodki** [comment]
closed because of inactivity, please reopen this issue if necessary
