### ISSUE TITLE
Matching processing doesn't proceed

### ISSUE THREAD

**Issue by paymonnb** [jagodki/Offline-MapMatching#45]
I'm matching trajectory with this two file.

But matching process didn't proceed from 3% while create backtracking.
I set clip network buffer to 0.001(I think it's degree unit) and max search distance to 50m.

How can I fix this problem?

<img width="407" alt="match_frozen" src="https://user-images.githubusercontent.com/83068124/115995180-33e37200-a615-11eb-944d-1522ba542f25.PNG">

crs is 5179
[sample.zip](https://github.com/jagodki/Offline-MapMatching/files/6372017/sample.zip)

**Comment by jagodki** [comment]
Hi, I can reproduce the problem, but I need some more time to find the problem. I will write you here, when I found a solution.

**Comment by paymonnb** [comment]
Thank you for your help. 

I will also try to figure it out.
