### ISSUE TITLE
How to use the model in a python script

### ISSUE THREAD

**Issue by Maxpicca-Li** [jagodki/Offline-MapMatching#46]
Hello, Jagodki. 

I have use this program in my QGIS. And it is received  a very good result. But I need to  process of trajectory data in a batch which may have thousands of data. And I have already read the `README.md` file. But I still haven't found how to use this model in a python script. And I have not yet understood where is the "process"  defined. So 
hope you have time to help me to solve this problem.

Sincerely,
Maxpicca

**Comment by jagodki** [comment]
Hello Maxpicca,

you have two possibilities to run the plugin in batch mode:
1. you can use the build-in batch mode accessible from each algorithm in the toolbox (disadvantage: you have to create and configure each repetition in the batch mode):
<img width="800" alt="Bildschirmfoto 2021-08-13 um 20 23 08" src="https://user-images.githubusercontent.com/23242936/129402866-59043661-00b1-4d50-a8ed-9091b611677e.png">

2. using the plugin via the processing framework in python. QGIS is shipped with a python framework called processing. Via this framework, you can call each algorithm and plugin that is available in your toolbox, i.e. the plugin Offline-MapMatching. The following python snippet is an example for the usage:
```
import processing
processing.run('omm:match_trajectory', {'NETWORK': 'network_layer',
                                        'TRAJECTORY': 'trajectory_layer',
                                        'TRAJECTORY_ID': 'id',
                                        'MAX_SEARCH_DISTANCE': 20.0,
                                        'OUTPUT': 'destination_in_filesystem'})
```

More information about the processing framework can be found in the QGIS documentation:
https://docs.qgis.org/3.16/en/docs/user_manual/processing/index.html

Best Regards,
Christoph

**Comment by Maxpicca-Li** [comment]
Oh, I see. Thanks!
